<?php declare(strict_types=1);

/**
 * PullLog API
 * ガチャ履歴管理アプリ「PullLog」バックエンドAPI仕様
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * AppData
 */
namespace App\Models;

/**
 * AppData
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class AppData
{
    /**
    *
    * アプリ名
    * @param string $name
    *
    * アプリID（ULID形式、ユーザーごとに一意）
    * @param string $appId
    *
    * アプリURL
    * @param null | string $url
    *
    * アプリ説明
    * @param null | string $description
    *
    * UI上の日付切替時刻（HH:mm形式）
    * @param null | string $dateUpdateTime
    *
    * true の場合、UIの日付切替時刻を当日の date_update_time に同期
    * @param bool $syncUpdateTime
    *
    * 通貨単位
    * @param null | string $currencyUnit
    *
    * レア排出保証システムの有無
    * @param null | bool $pitySystem
    *
    * レア排出保証回数（天井）
    * @param null | int $guaranteeCount
    *
    * レアリティ定義
    * @param null | \OpenAPI\Server\Model\SymbolOption[] $rarityDefs
    *
    * マーキング定義
    * @param null | \OpenAPI\Server\Model\SymbolOption[] $markerDefs
    *
    * タスク定義
    * @param null | \OpenAPI\Server\Model\SymbolOption[] $taskDefs
    */

    public function __construct(
        public string $name,
        public string $appId,
        public bool $syncUpdateTime,
        public ?string $url = null,
        public ?string $description = null,
        public ?string $dateUpdateTime = null,
        public ?string $currencyUnit = null,
        public ?bool $pitySystem = null,
        public ?int $guaranteeCount = null,
        public ?array $rarityDefs = null,
        public ?array $markerDefs = null,
        public ?array $taskDefs = null,
    ) {}
}

