<?php declare(strict_types=1);

/**
 * PullLog API
 * ガチャ履歴管理アプリ「PullLog」バックエンドAPI仕様
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * DateLog
 */
namespace App\Models;

/**
 * DateLog
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class DateLog
{
    /**
    *
    * アプリID
    * @param string $appId
    *
    * 記録日（YYYY-MM-DD）
    * @param \DateTime $date
    *
    * 当日ガチャ回数
    * @param int $totalPulls
    *
    * 当日レア排出数
    * @param int $dischargeItems
    *
    * レア排出詳細
    * @param \OpenAPI\Server\Model\DropDetail[] $dropDetails
    *
    * ガチャ費用合計
    * @param int $expense
    *
    * タグ（最大3つ）
    * @param string[] $tags
    *
    * フリーテキスト（max 200文字）
    * @param string $freeText
    *
    * 添付画像ファイルパス配列（将来機能）
    * @param string[] $images
    *
    * 完了タスク名配列（将来機能）
    * @param string[] $tasks
    *
    * 最終更新日時
    * @param null | \DateTime $lastUpdated
    */

    public function __construct(
        public string $appId,
        public \DateTime $date,
        public int $totalPulls,
        public int $dischargeItems,
        public array $dropDetails,
        public int $expense,
        public array $tags,
        public string $freeText,
        public array $images,
        public array $tasks,
        public ?\DateTime $lastUpdated = null,
    ) {}
}

