<?php declare(strict_types=1);

/**
 * PullLog API
 * ガチャ履歴管理アプリ「PullLog」バックエンドAPI仕様
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * DropDetail
 */
namespace App\Models;

/**
 * DropDetail
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class DropDetail
{
    /**
    *
    * レアリティ
    * @param null | string $rarity
    *
    * 排出アイテム名
    * @param null | string $name
    *
    * マーキング
    * @param null | string $marker
    */

    public function __construct(
        public ?string $rarity = null,
        public ?string $name = null,
        public ?string $marker = null,
    ) {}
}

