<?php declare(strict_types=1);

/**
 * PullLog API
 * ガチャ履歴管理アプリ「PullLog」バックエンドAPI仕様
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * LoginRequest
 */
namespace App\Models;

/**
 * LoginRequest
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class LoginRequest
{
    /**
    *
    * ログイン用メールアドレス
    * @param string $email
    *
    * パスワード（プレーンテキスト）
    * @param string $password
    *
    * Remember Me オプション。trueの場合、remember_tokenが返される
    * @param bool $remember
    */

    public function __construct(
        public string $email,
        public string $password,
        public bool $remember,
    ) {}
}

