<?php declare(strict_types=1);

/**
 * PullLog API
 * ガチャ履歴管理アプリ「PullLog」バックエンドAPI仕様
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * LoginResponse
 */
namespace App\Models;

/**
 * LoginResponse
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class LoginResponse
{
    /**
    *
    * 
    * @param \OpenAPI\Server\Model\LoginResponseState $state
    *
    * エラー時または補足時のメッセージ
    * @param null | string $message
    *
    * 
    * @param \OpenAPI\Server\Model\UserResponse $user
    *
    * CSRF対策用トークン
    * @param null | string $csrfToken
    *
    * Remember Meトークン（開発・Remember&#x3D;true時のみ）
    * @param null | string $rememberToken
    */

    public function __construct(
        public \OpenAPI\Server\Model\LoginResponseState $state,
        public \OpenAPI\Server\Model\UserResponse $user,
        public ?string $message = null,
        public ?string $csrfToken = null,
        public ?string $rememberToken = null,
    ) {}
}

