<?php declare(strict_types=1);

/**
 * PullLog API
 * ガチャ履歴管理アプリ「PullLog」バックエンドAPI仕様
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * PasswordUpdateRequest
 */
namespace App\Models;

/**
 * PasswordUpdateRequest
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class PasswordUpdateRequest
{
    /**
    *
    * 認証トークン（メール認証やリセットリンクに含まれる）
    * @param string $token
    *
    * 
    * @param \OpenAPI\Server\Model\PasswordUpdateRequestType $type
    *
    * 認証コード（メール本文等に記載のコード）
    * @param string $code
    *
    * 新しいパスワード
    * @param string $password
    */

    public function __construct(
        public string $token,
        public \OpenAPI\Server\Model\PasswordUpdateRequestType $type,
        public string $code,
        public string $password,
    ) {}
}

