<?php declare(strict_types=1);

/**
 * PullLog API
 * ガチャ履歴管理アプリ「PullLog」バックエンドAPI仕様
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * RegisterRequest
 */
namespace App\Models;

/**
 * RegisterRequest
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class RegisterRequest
{
    /**
    *
    * ユーザー表示名
    * @param string $name
    *
    * ログイン用メールアドレス
    * @param string $email
    *
    * パスワード
    * @param string $password
    *
    * 言語設定（例: ja, en）
    * @param string $language
    */

    public function __construct(
        public string $name,
        public string $email,
        public string $password,
        public string $language,
    ) {}
}

