<?php declare(strict_types=1);

/**
 * PullLog API
 * ガチャ履歴管理アプリ「PullLog」バックエンドAPI仕様
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * StatsData
 */
namespace App\Models;

/**
 * StatsData
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class StatsData
{
    /**
    *
    * 
    * @param string $appId
    *
    * 
    * @param \DateTime $startDate
    *
    * 
    * @param \DateTime $endDate
    *
    * 
    * @param int $totalPulls
    *
    * 
    * @param int $rareDropCount
    *
    * 
    * @param float $rareDropRate
    *
    * 
    * @param int $totalExpense
    *
    * 
    * @param float $averageExpense
    *
    * 
    * @param float $averageRareDropRate
    *
    * 
    * @param null | int $totalLogs
    *
    * 
    * @param null | int $monthsInPeriod
    *
    * 
    * @param null | float $averageMonthlyExpense
    */

    public function __construct(
        public string $appId,
        public \DateTime $startDate,
        public \DateTime $endDate,
        public int $totalPulls,
        public int $rareDropCount,
        public float $rareDropRate,
        public int $totalExpense,
        public float $averageExpense,
        public float $averageRareDropRate,
        public ?int $totalLogs = null,
        public ?int $monthsInPeriod = null,
        public ?float $averageMonthlyExpense = null,
    ) {}
}

