<?php declare(strict_types=1);

/**
 * PullLog API
 * ガチャ履歴管理アプリ「PullLog」バックエンドAPI仕様
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * SymbolOption
 */
namespace App\Models;

/**
 * SymbolOption
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class SymbolOption
{
    /**
    *
    * アイコン
    * @param null | string $icon
    *
    * シンボル
    * @param null | string $symbol
    *
    * ラベル
    * @param string $label
    *
    * オプション値（ULID形式で一意）
    * @param string $value
    *
    * 説明
    * @param null | string $desc
    *
    * 表示順
    * @param null | int $order
    */

    public function __construct(
        public string $label,
        public string $value,
        public ?string $icon = null,
        public ?string $symbol = null,
        public ?string $desc = null,
        public ?int $order = null,
    ) {}
}

