<?php declare(strict_types=1);

/**
 * PullLog API
 * ガチャ履歴管理アプリ「PullLog」バックエンドAPI仕様
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * UserPlanLimits
 */
namespace App\Models;

/**
 * UserPlanLimits
 * @description ユーザーの各種プラン上限値（動的キーも許可）
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class UserPlanLimits
{
    /**
    *
    * 
    * @param int $maxApps
    *
    * 
    * @param int $maxAppNameLength
    *
    * 
    * @param int $maxAppDescriptionLength
    *
    * 
    * @param int $maxLogTags
    *
    * 
    * @param int $maxLogTagLength
    *
    * 
    * @param int $maxLogTextLength
    *
    * 
    * @param int $maxLogsPerApp
    *
    * 
    * @param int $maxLogSize
    *
    * 
    * @param int $maxStorage
    */

    public function __construct(
        public int $maxApps,
        public int $maxAppNameLength,
        public int $maxAppDescriptionLength,
        public int $maxLogTags,
        public int $maxLogTagLength,
        public int $maxLogTextLength,
        public int $maxLogsPerApp,
        public int $maxLogSize,
        public int $maxStorage,
    ) {}
}

