<?php declare(strict_types=1);

/**
 * PullLog API
 * ガチャ履歴管理アプリ「PullLog」バックエンドAPI仕様
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * UserResponse
 */
namespace App\Models;

/**
 * UserResponse
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class UserResponse
{
    /**
    *
    * ユーザーID
    * @param int $id
    *
    * ユーザー名（表示名）
    * @param string $name
    *
    * メールアドレス
    * @param string $email
    *
    * アバター画像URL
    * @param null | string $avatarUrl
    *
    * ユーザー権限・役割（admin, user等）
    * @param string[] $roles
    *
    * ユーザープラン
    * @param string $plan
    *
    * プランの有効期限
    * @param null | \DateTime $planExpiration
    *
    * 
    * @param \OpenAPI\Server\Model\UserPlanLimits $planLimits
    *
    * ユーザーの言語設定
    * @param string $language
    *
    * テーマ設定
    * @param string $theme
    *
    * ログイン後のホームページ
    * @param string $homePage
    *
    * ユーザー登録日時
    * @param \DateTime $createdAt
    *
    * ユーザー情報更新日時
    * @param \DateTime $updatedAt
    *
    * 最終ログイン日時
    * @param \DateTime $lastLogin
    *
    * 最終ログインIPアドレス
    * @param null | string $lastLoginIp
    *
    * 最終ログイン時ユーザーエージェント
    * @param null | string $lastLoginUserAgent
    *
    * 論理削除フラグ
    * @param bool $isDeleted
    *
    * メール認証済みフラグ
    * @param bool $isVerified
    *
    * 未読通知ID一覧
    * @param int[] $unreadNotifications
    */

    public function __construct(
        public int $id,
        public string $name,
        public string $email,
        public array $roles,
        public string $plan,
        public \OpenAPI\Server\Model\UserPlanLimits $planLimits,
        public string $language,
        public string $theme,
        public string $homePage,
        public \DateTime $createdAt,
        public \DateTime $updatedAt,
        public \DateTime $lastLogin,
        public bool $isDeleted,
        public bool $isVerified,
        public array $unreadNotifications,
        public ?string $avatarUrl = null,
        public ?\DateTime $planExpiration = null,
        public ?string $lastLoginIp = null,
        public ?string $lastLoginUserAgent = null,
    ) {}
}

