<?php declare(strict_types=1);

/**
 * PullLog API
 * ガチャ履歴管理アプリ「PullLog」バックエンドAPI仕様
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * UserUpdateRequest
 */
namespace App\Models;

/**
 * UserUpdateRequest
 * @description ユーザー情報の部分更新（必要な項目のみ送信）
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class UserUpdateRequest
{
    /**
    *
    * 新しい表示名
    * @param string $name
    *
    * アバター画像URL（画像アップロード済みの場合）
    * @param string $avatarUrl
    *
    * 言語設定
    * @param string $language
    *
    * テーマ設定（light, dark など）
    * @param string $theme
    */

    public function __construct(
        public string $name,
        public string $avatarUrl,
        public string $language,
        public string $theme,
    ) {}
}

