<?php declare(strict_types=1);

/**
 * PullLog API
 * ガチャ履歴管理アプリ「PullLog」バックエンドAPI仕様
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * VerifyTokenRequestType
 */
namespace App\Models;

/**
 * VerifyTokenRequestType
 * @description 認証種別: signup（新規登録認証）または reset（パスワードリセット認証）
 */
enum VerifyTokenRequestType: string
{
        case SIGNUP = 'signup';
        case RESET = 'reset';
}
