<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrencySeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $rows = [
            ['code'=>'USD','name'=>'US Dollar','symbol'=>'$','symbol_native'=>'$','minor_unit'=>2,'rounding'=>0,'name_plural'=>'US dollars','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'CAD','name'=>'Canadian Dollar','symbol'=>'CA$','symbol_native'=>'$','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Canadian dollars','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'EUR','name'=>'Euro','symbol'=>'€','symbol_native'=>'€','minor_unit'=>2,'rounding'=>0,'name_plural'=>'euros','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'AED','name'=>'United Arab Emirates Dirham','symbol'=>'AED','symbol_native'=>'د.إ.‏','minor_unit'=>2,'rounding'=>0,'name_plural'=>'UAE dirhams','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'AFN','name'=>'Afghan Afghani','symbol'=>'Af','symbol_native'=>'؋','minor_unit'=>0,'rounding'=>0,'name_plural'=>'Afghan Afghanis','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'ALL','name'=>'Albanian Lek','symbol'=>'ALL','symbol_native'=>'Lek','minor_unit'=>0,'rounding'=>0,'name_plural'=>'Albanian lekë','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'AMD','name'=>'Armenian Dram','symbol'=>'AMD','symbol_native'=>'դր.','minor_unit'=>0,'rounding'=>0,'name_plural'=>'Armenian drams','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'ARS','name'=>'Argentine Peso','symbol'=>'AR$','symbol_native'=>'$','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Argentine pesos','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'AUD','name'=>'Australian Dollar','symbol'=>'AU$','symbol_native'=>'$','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Australian dollars','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'AZN','name'=>'Azerbaijani Manat','symbol'=>'man.','symbol_native'=>'ман.','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Azerbaijani manats','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'BAM','name'=>'Bosnia-Herzegovina Convertible Mark','symbol'=>'KM','symbol_native'=>'KM','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Bosnia-Herzegovina convertible marks','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'BDT','name'=>'Bangladeshi Taka','symbol'=>'Tk','symbol_native'=>'৳','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Bangladeshi takas','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'BGN','name'=>'Bulgarian Lev','symbol'=>'BGN','symbol_native'=>'лв.','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Bulgarian leva','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'BHD','name'=>'Bahraini Dinar','symbol'=>'BD','symbol_native'=>'د.ب.‏','minor_unit'=>3,'rounding'=>0,'name_plural'=>'Bahraini dinars','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'BIF','name'=>'Burundian Franc','symbol'=>'FBu','symbol_native'=>'FBu','minor_unit'=>0,'rounding'=>0,'name_plural'=>'Burundian francs','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'BND','name'=>'Brunei Dollar','symbol'=>'BN$','symbol_native'=>'$','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Brunei dollars','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'BOB','name'=>'Bolivian Boliviano','symbol'=>'Bs','symbol_native'=>'Bs','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Bolivian bolivianos','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'BRL','name'=>'Brazilian Real','symbol'=>'R$','symbol_native'=>'R$','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Brazilian reals','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'BWP','name'=>'Botswanan Pula','symbol'=>'BWP','symbol_native'=>'P','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Botswanan pulas','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'BYN','name'=>'Belarusian Ruble','symbol'=>'Br','symbol_native'=>'руб.','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Belarusian rubles','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'BZD','name'=>'Belize Dollar','symbol'=>'BZ$','symbol_native'=>'$','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Belize dollars','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'CDF','name'=>'Congolese Franc','symbol'=>'CDF','symbol_native'=>'FrCD','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Congolese francs','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'CHF','name'=>'Swiss Franc','symbol'=>'CHF','symbol_native'=>'CHF','minor_unit'=>2,'rounding'=>0.05,'name_plural'=>'Swiss francs','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'CLP','name'=>'Chilean Peso','symbol'=>'CL$','symbol_native'=>'$','minor_unit'=>0,'rounding'=>0,'name_plural'=>'Chilean pesos','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'CNY','name'=>'Chinese Yuan','symbol'=>'CN¥','symbol_native'=>'CN¥','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Chinese yuan','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'COP','name'=>'Colombian Peso','symbol'=>'CO$','symbol_native'=>'$','minor_unit'=>0,'rounding'=>0,'name_plural'=>'Colombian pesos','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'CRC','name'=>'Costa Rican Colón','symbol'=>'₡','symbol_native'=>'₡','minor_unit'=>0,'rounding'=>0,'name_plural'=>'Costa Rican colóns','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'CVE','name'=>'Cape Verdean Escudo','symbol'=>'CV$','symbol_native'=>'CV$','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Cape Verdean escudos','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'CZK','name'=>'Czech Republic Koruna','symbol'=>'Kč','symbol_native'=>'Kč','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Czech Republic korunas','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'DJF','name'=>'Djiboutian Franc','symbol'=>'Fdj','symbol_native'=>'Fdj','minor_unit'=>0,'rounding'=>0,'name_plural'=>'Djiboutian francs','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'DKK','name'=>'Danish Krone','symbol'=>'Dkr','symbol_native'=>'kr','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Danish kroner','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'DOP','name'=>'Dominican Peso','symbol'=>'RD$','symbol_native'=>'RD$','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Dominican pesos','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'DZD','name'=>'Algerian Dinar','symbol'=>'DA','symbol_native'=>'د.ج.‏','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Algerian dinars','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'EEK','name'=>'Estonian Kroon','symbol'=>'Ekr','symbol_native'=>'kr','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Estonian kroons','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'EGP','name'=>'Egyptian Pound','symbol'=>'EGP','symbol_native'=>'ج.م.‏','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Egyptian pounds','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'ERN','name'=>'Eritrean Nakfa','symbol'=>'Nfk','symbol_native'=>'Nfk','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Eritrean nakfas','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'ETB','name'=>'Ethiopian Birr','symbol'=>'Br','symbol_native'=>'Br','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Ethiopian birrs','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'GBP','name'=>'British Pound Sterling','symbol'=>'£','symbol_native'=>'£','minor_unit'=>2,'rounding'=>0,'name_plural'=>'British pounds sterling','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'GEL','name'=>'Georgian Lari','symbol'=>'GEL','symbol_native'=>'GEL','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Georgian laris','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'GHS','name'=>'Ghanaian Cedi','symbol'=>'GH₵','symbol_native'=>'GH₵','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Ghanaian cedis','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'GNF','name'=>'Guinean Franc','symbol'=>'FG','symbol_native'=>'FG','minor_unit'=>0,'rounding'=>0,'name_plural'=>'Guinean francs','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'GTQ','name'=>'Guatemalan Quetzal','symbol'=>'GTQ','symbol_native'=>'Q','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Guatemalan quetzals','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'HKD','name'=>'Hong Kong Dollar','symbol'=>'HK$','symbol_native'=>'$','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Hong Kong dollars','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'HNL','name'=>'Honduran Lempira','symbol'=>'HNL','symbol_native'=>'L','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Honduran lempiras','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'HRK','name'=>'Croatian Kuna','symbol'=>'kn','symbol_native'=>'kn','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Croatian kunas','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'HUF','name'=>'Hungarian Forint','symbol'=>'Ft','symbol_native'=>'Ft','minor_unit'=>0,'rounding'=>0,'name_plural'=>'Hungarian forints','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'IDR','name'=>'Indonesian Rupiah','symbol'=>'Rp','symbol_native'=>'Rp','minor_unit'=>0,'rounding'=>0,'name_plural'=>'Indonesian rupiahs','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'ILS','name'=>'Israeli New Sheqel','symbol'=>'₪','symbol_native'=>'₪','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Israeli new sheqels','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'INR','name'=>'Indian Rupee','symbol'=>'Rs','symbol_native'=>'টকা','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Indian rupees','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'IQD','name'=>'Iraqi Dinar','symbol'=>'IQD','symbol_native'=>'د.ع.‏','minor_unit'=>0,'rounding'=>0,'name_plural'=>'Iraqi dinars','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'IRR','name'=>'Iranian Rial','symbol'=>'IRR','symbol_native'=>'﷼','minor_unit'=>0,'rounding'=>0,'name_plural'=>'Iranian rials','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'ISK','name'=>'Icelandic Króna','symbol'=>'Ikr','symbol_native'=>'kr','minor_unit'=>0,'rounding'=>0,'name_plural'=>'Icelandic krónur','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'JMD','name'=>'Jamaican Dollar','symbol'=>'J$','symbol_native'=>'$','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Jamaican dollars','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'JOD','name'=>'Jordanian Dinar','symbol'=>'JD','symbol_native'=>'د.أ.‏','minor_unit'=>3,'rounding'=>0,'name_plural'=>'Jordanian dinars','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'JPY','name'=>'Japanese Yen','symbol'=>'¥','symbol_native'=>'￥','minor_unit'=>0,'rounding'=>0,'name_plural'=>'Japanese yen','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'KES','name'=>'Kenyan Shilling','symbol'=>'Ksh','symbol_native'=>'Ksh','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Kenyan shillings','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'KHR','name'=>'Cambodian Riel','symbol'=>'KHR','symbol_native'=>'៛','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Cambodian riels','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'KMF','name'=>'Comorian Franc','symbol'=>'CF','symbol_native'=>'FC','minor_unit'=>0,'rounding'=>0,'name_plural'=>'Comorian francs','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'KRW','name'=>'South Korean Won','symbol'=>'₩','symbol_native'=>'₩','minor_unit'=>0,'rounding'=>0,'name_plural'=>'South Korean won','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'KWD','name'=>'Kuwaiti Dinar','symbol'=>'KD','symbol_native'=>'د.ك.‏','minor_unit'=>3,'rounding'=>0,'name_plural'=>'Kuwaiti dinars','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'KZT','name'=>'Kazakhstani Tenge','symbol'=>'KZT','symbol_native'=>'тңг.','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Kazakhstani tenges','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'LBP','name'=>'Lebanese Pound','symbol'=>'L.L.','symbol_native'=>'ل.ل.‏','minor_unit'=>0,'rounding'=>0,'name_plural'=>'Lebanese pounds','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'LKR','name'=>'Sri Lankan Rupee','symbol'=>'SLRs','symbol_native'=>'SL Re','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Sri Lankan rupees','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'LTL','name'=>'Lithuanian Litas','symbol'=>'Lt','symbol_native'=>'Lt','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Lithuanian litai','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'LVL','name'=>'Latvian Lats','symbol'=>'Ls','symbol_native'=>'Ls','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Latvian lati','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'LYD','name'=>'Libyan Dinar','symbol'=>'LD','symbol_native'=>'د.ل.‏','minor_unit'=>3,'rounding'=>0,'name_plural'=>'Libyan dinars','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'MAD','name'=>'Moroccan Dirham','symbol'=>'MAD','symbol_native'=>'د.م.‏','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Moroccan dirhams','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'MDL','name'=>'Moldovan Leu','symbol'=>'MDL','symbol_native'=>'MDL','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Moldovan lei','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'MGA','name'=>'Malagasy Ariary','symbol'=>'MGA','symbol_native'=>'MGA','minor_unit'=>0,'rounding'=>0,'name_plural'=>'Malagasy Ariaries','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'MKD','name'=>'Macedonian Denar','symbol'=>'MKD','symbol_native'=>'MKD','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Macedonian denari','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'MMK','name'=>'Myanma Kyat','symbol'=>'MMK','symbol_native'=>'K','minor_unit'=>0,'rounding'=>0,'name_plural'=>'Myanma kyats','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'MOP','name'=>'Macanese Pataca','symbol'=>'MOP$','symbol_native'=>'MOP$','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Macanese patacas','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'MUR','name'=>'Mauritian Rupee','symbol'=>'MURs','symbol_native'=>'MURs','minor_unit'=>0,'rounding'=>0,'name_plural'=>'Mauritian rupees','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'MXN','name'=>'Mexican Peso','symbol'=>'MX$','symbol_native'=>'$','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Mexican pesos','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'MYR','name'=>'Malaysian Ringgit','symbol'=>'RM','symbol_native'=>'RM','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Malaysian ringgits','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'MZN','name'=>'Mozambican Metical','symbol'=>'MTn','symbol_native'=>'MTn','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Mozambican meticals','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'NAD','name'=>'Namibian Dollar','symbol'=>'N$','symbol_native'=>'N$','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Namibian dollars','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'NGN','name'=>'Nigerian Naira','symbol'=>'₦','symbol_native'=>'₦','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Nigerian nairas','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'NIO','name'=>'Nicaraguan Córdoba','symbol'=>'C$','symbol_native'=>'C$','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Nicaraguan córdobas','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'NOK','name'=>'Norwegian Krone','symbol'=>'Nkr','symbol_native'=>'kr','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Norwegian kroner','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'NPR','name'=>'Nepalese Rupee','symbol'=>'NPRs','symbol_native'=>'नेरू','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Nepalese rupees','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'NZD','name'=>'New Zealand Dollar','symbol'=>'NZ$','symbol_native'=>'$','minor_unit'=>2,'rounding'=>0,'name_plural'=>'New Zealand dollars','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'OMR','name'=>'Omani Rial','symbol'=>'OMR','symbol_native'=>'ر.ع.‏','minor_unit'=>3,'rounding'=>0,'name_plural'=>'Omani rials','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'PAB','name'=>'Panamanian Balboa','symbol'=>'B/.','symbol_native'=>'B/.','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Panamanian balboas','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'PEN','name'=>'Peruvian Nuevo Sol','symbol'=>'S/.','symbol_native'=>'S/.','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Peruvian nuevos soles','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'PHP','name'=>'Philippine Peso','symbol'=>'₱','symbol_native'=>'₱','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Philippine pesos','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'PKR','name'=>'Pakistani Rupee','symbol'=>'PKRs','symbol_native'=>'₨','minor_unit'=>0,'rounding'=>0,'name_plural'=>'Pakistani rupees','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'PLN','name'=>'Polish Zloty','symbol'=>'zł','symbol_native'=>'zł','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Polish zlotys','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'PYG','name'=>'Paraguayan Guarani','symbol'=>'₲','symbol_native'=>'₲','minor_unit'=>0,'rounding'=>0,'name_plural'=>'Paraguayan guaranis','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'QAR','name'=>'Qatari Rial','symbol'=>'QR','symbol_native'=>'ر.ق.‏','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Qatari rials','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'RON','name'=>'Romanian Leu','symbol'=>'RON','symbol_native'=>'RON','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Romanian lei','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'RSD','name'=>'Serbian Dinar','symbol'=>'din.','symbol_native'=>'дин.','minor_unit'=>0,'rounding'=>0,'name_plural'=>'Serbian dinars','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'RUB','name'=>'Russian Ruble','symbol'=>'RUB','symbol_native'=>'₽.','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Russian rubles','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'RWF','name'=>'Rwandan Franc','symbol'=>'RWF','symbol_native'=>'FR','minor_unit'=>0,'rounding'=>0,'name_plural'=>'Rwandan francs','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'SAR','name'=>'Saudi Riyal','symbol'=>'SR','symbol_native'=>'ر.س.‏','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Saudi riyals','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'SDG','name'=>'Sudanese Pound','symbol'=>'SDG','symbol_native'=>'SDG','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Sudanese pounds','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'SEK','name'=>'Swedish Krona','symbol'=>'Skr','symbol_native'=>'kr','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Swedish kronor','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'SGD','name'=>'Singapore Dollar','symbol'=>'S$','symbol_native'=>'$','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Singapore dollars','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'SOS','name'=>'Somali Shilling','symbol'=>'Ssh','symbol_native'=>'Ssh','minor_unit'=>0,'rounding'=>0,'name_plural'=>'Somali shillings','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'SYP','name'=>'Syrian Pound','symbol'=>'SY£','symbol_native'=>'ل.س.‏','minor_unit'=>0,'rounding'=>0,'name_plural'=>'Syrian pounds','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'THB','name'=>'Thai Baht','symbol'=>'฿','symbol_native'=>'฿','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Thai baht','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'TND','name'=>'Tunisian Dinar','symbol'=>'DT','symbol_native'=>'د.ت.‏','minor_unit'=>3,'rounding'=>0,'name_plural'=>'Tunisian dinars','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'TOP','name'=>'Tongan Paʻanga','symbol'=>'T$','symbol_native'=>'T$','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Tongan paʻanga','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'TRY','name'=>'Turkish Lira','symbol'=>'TL','symbol_native'=>'TL','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Turkish Lira','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'TTD','name'=>'Trinidad and Tobago Dollar','symbol'=>'TT$','symbol_native'=>'$','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Trinidad and Tobago dollars','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'TWD','name'=>'New Taiwan Dollar','symbol'=>'NT$','symbol_native'=>'NT$','minor_unit'=>2,'rounding'=>0,'name_plural'=>'New Taiwan dollars','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'TZS','name'=>'Tanzanian Shilling','symbol'=>'TSh','symbol_native'=>'TSh','minor_unit'=>0,'rounding'=>0,'name_plural'=>'Tanzanian shillings','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'UAH','name'=>'Ukrainian Hryvnia','symbol'=>'₴','symbol_native'=>'₴','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Ukrainian hryvnias','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'UGX','name'=>'Ugandan Shilling','symbol'=>'USh','symbol_native'=>'USh','minor_unit'=>0,'rounding'=>0,'name_plural'=>'Ugandan shillings','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'UYU','name'=>'Uruguayan Peso','symbol'=>'$U','symbol_native'=>'$','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Uruguayan pesos','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'UZS','name'=>'Uzbekistan Som','symbol'=>'UZS','symbol_native'=>'UZS','minor_unit'=>0,'rounding'=>0,'name_plural'=>'Uzbekistan som','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'VEF','name'=>'Venezuelan Bolívar','symbol'=>'Bs.F.','symbol_native'=>'Bs.F.','minor_unit'=>2,'rounding'=>0,'name_plural'=>'Venezuelan bolívars','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'VND','name'=>'Vietnamese Dong','symbol'=>'₫','symbol_native'=>'₫','minor_unit'=>0,'rounding'=>0,'name_plural'=>'Vietnamese dong','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'XAF','name'=>'CFA Franc BEAC','symbol'=>'FCFA','symbol_native'=>'FCFA','minor_unit'=>0,'rounding'=>0,'name_plural'=>'CFA francs BEAC','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'XOF','name'=>'CFA Franc BCEAO','symbol'=>'CFA','symbol_native'=>'CFA','minor_unit'=>0,'rounding'=>0,'name_plural'=>'CFA francs BCEAO','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'YER','name'=>'Yemeni Rial','symbol'=>'YR','symbol_native'=>'ر.ي.‏','minor_unit'=>0,'rounding'=>0,'name_plural'=>'Yemeni rials','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'ZAR','name'=>'South African Rand','symbol'=>'R','symbol_native'=>'R','minor_unit'=>2,'rounding'=>0,'name_plural'=>'South African rand','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'ZMK','name'=>'Zambian Kwacha','symbol'=>'ZK','symbol_native'=>'ZK','minor_unit'=>0,'rounding'=>0,'name_plural'=>'Zambian kwachas','created_at'=>$now,'updated_at'=>$now],
            ['code'=>'ZWL','name'=>'Zimbabwean Dollar','symbol'=>'ZWL$','symbol_native'=>'ZWL$','minor_unit'=>0,'rounding'=>0,'name_plural'=>'Zimbabwean Dollar','created_at'=>$now,'updated_at'=>$now],
        ];

        // まとめてUPSERT
        DB::table('currencies')->upsert(
            $rows,
            uniqueBy: ['code'],
            update: ['name','symbol','symbol_native','minor_unit','rounding','name_plural','updated_at']
        );
    }
}
