<?php declare(strict_types=1);

/**
 * PullLog API
 * ガチャ履歴管理アプリ「PullLog」バックエンドAPI仕様
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace OpenAPI\Server\Api;


interface DefaultApiInterface {


    /**
     * Operation appsAppIdDelete
     *
     * アプリの削除
     * @param string $appId
     * @return \App\Models\DeleteResponse | \App\Models\NoContent401
     */
    public function appsAppIdDelete(
            string $appId,
    ):
        \App\Models\DeleteResponse | 
        \App\Models\NoContent401
    ;


    /**
     * Operation appsAppIdGet
     *
     * 単一アプリデータ取得
     * @param string $appId
     * @return \OpenAPIServerModelAppData | \App\Models\AppsAppIdGet404Response | \App\Models\NoContent401
     */
    public function appsAppIdGet(
            string $appId,
    ):
        \OpenAPIServerModelAppData | 
        \App\Models\AppsAppIdGet404Response | 
        \App\Models\NoContent401
    ;


    /**
     * Operation appsAppIdPut
     *
     * アプリデータ更新
     * @param string $appId
     * @param \App\Models\AppData $appData
     * @return \App\Models\AppData | \App\Models\NoContent400 | \App\Models\NoContent404 | \App\Models\NoContent401
     */
    public function appsAppIdPut(
            string $appId,
            \App\Models\AppData $appData,
    ):
        \App\Models\AppData | 
        \App\Models\NoContent400 | 
        \App\Models\NoContent404 | 
        \App\Models\NoContent401
    ;


    /**
     * Operation appsGet
     *
     * ユーザーの登録アプリ一覧取得
     * @return \App\Models\AppData[] | \App\Models\NoContent401
     */
    public function appsGet(
    ):
        array | 
        \App\Models\NoContent401
    ;


    /**
     * Operation appsPost
     *
     * アプリ新規登録
     * @param \App\Models\AppData $appData
     * @return \App\Models\AppData | \App\Models\NoContent400 | \App\Models\NoContent401
     */
    public function appsPost(
            \App\Models\AppData $appData,
    ):
        \App\Models\AppData | 
        \App\Models\NoContent400 | 
        \App\Models\NoContent401
    ;


    /**
     * Operation authAutologinPost
     *
     * 自動ログイン
     * @return \App\Models\LoginResponse
     */
    public function authAutologinPost(
    ):
        \App\Models\LoginResponse
    ;


    /**
     * Operation authLoginPost
     *
     * ユーザーログイン
     * @param \App\Models\LoginRequest $loginRequest
     * @return \App\Models\LoginResponse | \App\Models\NoContent500
     */
    public function authLoginPost(
            \App\Models\LoginRequest $loginRequest,
    ):
        \App\Models\LoginResponse | 
        \App\Models\NoContent500
    ;


    /**
     * Operation authLogoutPost
     *
     * ユーザーログアウト
     * @return \App\Models\VerifyResponse
     */
    public function authLogoutPost(
    ):
        \App\Models\VerifyResponse
    ;


    /**
     * Operation authPasswordPost
     *
     * パスワード再設定リクエスト
     * @param \App\Models\PasswordResetRequest $passwordResetRequest
     * @return \App\Models\PasswordResetResponse
     */
    public function authPasswordPost(
            \App\Models\PasswordResetRequest $passwordResetRequest,
    ):
        \App\Models\PasswordResetResponse
    ;


    /**
     * Operation authPasswordPut
     *
     * パスワード再設定・確定
     * @param \App\Models\PasswordUpdateRequest $passwordUpdateRequest
     * @return \App\Models\VerifyResponse
     */
    public function authPasswordPut(
            \App\Models\PasswordUpdateRequest $passwordUpdateRequest,
    ):
        \App\Models\VerifyResponse
    ;


    /**
     * Operation authRegisterPost
     *
     * アカウント新規登録
     * @param \App\Models\RegisterRequest $registerRequest
     * @return \App\Models\RegisterResponse
     */
    public function authRegisterPost(
            \App\Models\RegisterRequest $registerRequest,
    ):
        \App\Models\RegisterResponse
    ;


    /**
     * Operation authVerifyPost
     *
     * メール認証トークン受付
     * @param \App\Models\VerifyTokenRequest $verifyTokenRequest
     * @return \App\Models\VerifyResponse
     */
    public function authVerifyPost(
            \App\Models\VerifyTokenRequest $verifyTokenRequest,
    ):
        \App\Models\VerifyResponse
    ;


    /**
     * Operation logsAppIdGet
     *
     * アプリの日次ログ一覧取得
     * @param string $appId
     * @param null | \DateTime $from
     * @param null | \DateTime $to
     * @param null | int $limit
     * @param null | int $offset
     * @return \App\Models\DateLog[] | \App\Models\NoContent400 | \App\Models\NoContent401 | \App\Models\NoContent404
     */
    public function logsAppIdGet(
            string $appId,
            ?\DateTime $from,
            ?\DateTime $to,
            ?int $limit,
            ?int $offset,
    ):
        array | 
        \App\Models\NoContent400 | 
        \App\Models\NoContent401 | 
        \App\Models\NoContent404
    ;


    /**
     * Operation logsDailyAppIdDateDelete
     *
     * 日次ログデータの削除
     * @param string $appId
     * @param \DateTime $date
     * @return \App\Models\DeleteResponse | \App\Models\NoContent401 | \App\Models\NoContent400
     */
    public function logsDailyAppIdDateDelete(
            string $appId,
            \DateTime $date,
    ):
        \App\Models\DeleteResponse | 
        \App\Models\NoContent401 | 
        \App\Models\NoContent400
    ;


    /**
     * Operation logsDailyAppIdDateGet
     *
     * 指定アプリ・日付の日次ログデータ取得
     * @param string $appId
     * @param \DateTime $date
     * @return \App\Models\DateLog | \App\Models\LogsDailyAppIdDateGet404Response | \App\Models\NoContent401
     */
    public function logsDailyAppIdDateGet(
            string $appId,
            \DateTime $date,
    ):
        \App\Models\DateLog | 
        \App\Models\LogsDailyAppIdDateGet404Response | 
        \App\Models\NoContent401
    ;


    /**
     * Operation logsDailyAppIdDatePost
     *
     * 日次ログの新規登録
     * @param string $appId
     * @param \DateTime $date
     * @param \App\Models\DateLog $dateLog
     * @return \App\Models\DateLog | \App\Models\NoContent400 | \App\Models\NoContent401 | \App\Models\NoContent409
     */
    public function logsDailyAppIdDatePost(
            string $appId,
            \DateTime $date,
            \App\Models\DateLog $dateLog,
    ):
        \App\Models\DateLog | 
        \App\Models\NoContent400 | 
        \App\Models\NoContent401 | 
        \App\Models\NoContent409
    ;


    /**
     * Operation logsDailyAppIdDatePut
     *
     * 日次ログの更新
     * @param string $appId
     * @param \DateTime $date
     * @param \App\Models\DateLog $dateLog
     * @return \App\Models\DateLog | \App\Models\NoContent400 | \App\Models\NoContent401 | \App\Models\NoContent404
     */
    public function logsDailyAppIdDatePut(
            string $appId,
            \DateTime $date,
            \App\Models\DateLog $dateLog,
    ):
        \App\Models\DateLog | 
        \App\Models\NoContent400 | 
        \App\Models\NoContent401 | 
        \App\Models\NoContent404
    ;


    /**
     * Operation logsImportAppIdPost
     *
     * ログデータのバルクインポート
     * @param string $appId
     * @param \App\Models\LogsImportAppIdPostModeParameter $mode
     * @param \Illuminate\Http\UploadedFile $file
     * @return \App\Models\ImportLogsResponse | \App\Models\NoContent400 | \App\Models\NoContent401
     */
    public function logsImportAppIdPost(
            string $appId,
            \App\Models\LogsImportAppIdPostModeParameter $mode,
            \Illuminate\Http\UploadedFile $file,
    ):
        \App\Models\ImportLogsResponse | 
        \App\Models\NoContent400 | 
        \App\Models\NoContent401
    ;


    /**
     * Operation statsAppIdGet
     *
     * アプリ単位の統計データ取得
     * @param string $appId
     * @param \DateTime $start
     * @param \DateTime $end
     * @return \App\Models\StatsData | \App\Models\NoContent400 | \App\Models\NoContent401 | \App\Models\NoContent404
     */
    public function statsAppIdGet(
            string $appId,
            \DateTime $start,
            \DateTime $end,
    ):
        \App\Models\StatsData | 
        \App\Models\NoContent400 | 
        \App\Models\NoContent401 | 
        \App\Models\NoContent404
    ;


    /**
     * Operation userUpdatePut
     *
     * ユーザープロフィール更新
     * @param \App\Models\UserUpdateRequest $userUpdateRequest
     * @return \App\Models\UserUpdateResponse | \App\Models\NoContent401
     */
    public function userUpdatePut(
            \App\Models\UserUpdateRequest $userUpdateRequest,
    ):
        \App\Models\UserUpdateResponse | 
        \App\Models\NoContent401
    ;

}
